"""First migration1

Revision ID: 236936dee1c4
Revises: 
Create Date: 2022-12-13 17:08:53.986790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236936dee1c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('patronymic', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=False),
    sa.Column('appeal_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appeals_id'), 'appeals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appeals_id'), table_name='appeals')
    op.drop_table('appeals')
    # ### end Alembic commands ###
